[package]
name = "hlist-serde-playground"
version = "0.1.0"
edition = "2021"

[dependencies]
frunk_core = { version = "0.4", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"